[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

